#### Admin CMS APIs



### root api
GET http://localhost:8000/


### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
   "fname": "Divyesh", 
   "lname": "Shrestha", 
   "email": "j@b.com",
   "dob": "2021-10-10",
   "password": "123456dgdg",
    "phone": "000000450757589",
    "address": "Sydney , NSW",
    "gender": "male"
    
}

//server side validation
//send email confirmation
//validate email
//account has been activated